-- Vyapara Gateway Admin Dashboard Database Documentation
-- This file documents the existing database structure - DO NOT EXECUTE
-- Database is already set up in production

-- Example application data structure:
-- {
--   "id": "be197fd9-8968-4575-be8e-c76b0d6ce062",
--   "business_id": "3efae37e-92df-4cd4-8281-ac3adf08a866", 
--   "applicant_id": "f33c9ed4-2140-42cd-ae22-19c1c7522e04",
--   "application_number": "VG202508000003",
--   "status": "submitted",
--   "current_step": "document_review",
--   "total_steps": 5,
--   "completed_steps": 5,
--   "submitted_at": "2025-08-16 11:54:44.596892+00",
--   "approved_at": null,
--   "rejected_at": null,
--   "rejection_reason": null,
--   "estimated_completion_date": null,
--   "notes": null,
--   "created_at": "2025-08-16 06:24:44.822891+00",
--   "updated_at": "2025-08-16 06:24:44.822891+00"
-- }

-- Application Status Flow:
-- draft -> submitted -> document_review -> approved/rejected
-- 
-- When reviewing documents:
-- 1. Admin can approve: status -> 'approved', approved_at -> timestamp
-- 2. Admin can reject: status -> 'rejected', rejected_at -> timestamp, rejection_reason -> text
-- 3. Admin can request changes: status -> 'revision_required', notes -> feedback

-- Key Tables Used:
-- - business_applications (main application data)
-- - application_documents (uploaded documents)
-- - businesses (business information)
-- - user_profiles (applicant information)
